import { Box } from "@mui/material";
import React from "react";

export const Home = () => {
  return (
    <>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
      <Box>Home</Box>
    </>
  );
};
